# +============================+

nextcloud_domain: nc.com
nextcloud_username: talel
nextcloud_userpass: talelpass

# +============================+

php_version: 7.2

# +============================+

port_http: 81
port_ssl: 443

# +============================+

autocloud_dir: /opt/auto-cloud

# +============================+

talk_static_auth_secret: 75b56f192cfd8541e084e5957cc8c1478144b38dc25aa34aa91f33c3d8ef4100

# +============================+

debian_repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} contrib"
package_repo: "deb http://download.onlyoffice.com/repo/debian squeeze main"
onlyoffice_default_config: /etc/onlyoffice/documentserver/local.json
json: json -q -f {{ onlyoffice_default_config }}
filestorage_mount_path: /var/lib/onlyoffice/documentserver/App_Data/cache/files
fonts_mount_path: /usr/share/fonts
psql: "PGPASSWORD={{ onlyoffice_userpass }} psql -q -h localhost -U{{ onlyoffice_username }} -w -d onlyoffice"
createdb_sql: /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql

# +============================+

redis_server_host: localhost
redis_server_port: 6379

# +============================+

rabbitmq_server_host: localhost
rabbitmq_server_user: guest
rabbitmq_server_pass: guest
rabbitmq_server_vpath: /
rabbitmq_server_url: "amqp://{{ rabbitmq_server_user }}:{{ rabbitmq_server_pass }}@{{ rabbitmq_server_host }}{{ rabbitmq_server_vpath }}"

# +============================+

package_name: onlyoffice-documentserver

# +============================+

onlyoffice_username: 
onlyoffice_userpass: 
onlyoffice_domain:

# +============================+

email: talel

# +============================+

onlyoffice_with_nextcloud: 

# +============================+

state: l

# +============================+

collabora_domain:

# +============================+

webserver: n

# +============================+

dbtype: mysql

# +============================+