- name: Installing coturn
  apt:
   name: coturn
   state: latest
  become: yes

- name: enable coturn
  systemd:
    name: coturn
    state: started
    enabled: true

- name: enable coturn
  lineinfile:
    path: /etc/default/coturn
    regexp: '(.*)TURNSERVER_ENABLED=(.*)'
    line:   'TURNSERVER_ENABLED=1'
    backup: true
  notify: restart coturn

- name: bring /etc/turnserver.conf in place
  template:
    src:  turnserver.conf.j2
    dest: /etc/turnserver.conf
    owner: root
    group: root
    mode:  0644
    force: true
  notify:  restart coturn

- name: install talk app
  shell: sudo -u www-data php occ app:install spreed
  args:
    chdir: /var/www/nextcloud/
    creates: /var/www/nextcloud/apps/spreed

- name: enable talk app
  shell: sudo -u www-data php occ app:enable spreed
  args:
    chdir: /var/www/nextcloud/

- name: set stun_server
  shell: sudo -u www-data php occ config:app:set spreed stun_servers --value '["{{ nextcloud_domain }}:5349"]'
  args:
    chdir: /var/www/nextcloud/

- name: set turn server
  shell: sudo -u www-data php occ config:app:set spreed turn_servers --value '[{"server":"{{ nextcloud_domain }}:5349","secret":"{{ talk_static_auth_secret }}","protocols":"udp,tcp"}]'
  args:
    chdir: /var/www/nextcloud/
    
- name: open ufw firewall
  include_role:
    name: ufw
  vars:
    ufw_applications: 
      - { name: TurnServer, rule: allow, from_ip: any }