---
# handlers file for prep_collabora

- name: restart collabora container
  shell: docker restart collabora_online
#  docker_container:
#    name: collabra_online
#    state: started
#    restart: yes

- name: restart apache2
  service:
    name: apache2
    state: restarted
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
