
# nextcloud domain for nginx configuration
nextcloud_domain: nextcloud.example.org

# Official nextcloud download link
# version 20.0.5 set in 16/01/2021
nextcloud_package_link: https://download.nextcloud.com/server/releases/nextcloud-20.0.5.zip

# MySQL nextcloud user credentials
nextcloud_username: nextcloud
nextcloud_userpass: nextcloud
nextcloud_cfile:

# MySQL nextcloud database credentials (user must be exist)
nextcloud_db_user: root
nextcloud_db_password: root
nextcloud_db_name: nextcloud

# Let it empty, the main script will set it for you :)
autocloud_dir: /home/talel/Documents/personal_github/auto-cloud

php_version: 7.2

talk_static_auth_secret: 75b56f192cfd8541e084e5957cc8c1478144b38dc25aa34aa91f33c3d8ef4100

# +============================+

debian_repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} contrib"
package_repo: "deb http://download.onlyoffice.com/repo/debian squeeze main"
onlyoffice_default_config: /etc/onlyoffice/documentserver/local.json
json: json -q -f {{ onlyoffice_default_config }}
filestorage_mount_path: /var/lib/onlyoffice/documentserver/App_Data/cache/files
fonts_mount_path: /usr/share/fonts
psql: "PGPASSWORD={{ onlyoffice_userpass }} psql -q -h localhost -U{{ onlyoffice_username }} -w -d onlyoffice"
createdb_sql: /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql

# +============================+

redis_server_host: localhost
redis_server_port: 6379

# +============================+

rabbitmq_server_host: localhost
rabbitmq_server_user: guest
rabbitmq_server_pass: guest
rabbitmq_server_vpath: /
rabbitmq_server_url: "amqp://{{ rabbitmq_server_user }}:{{ rabbitmq_server_pass }}@{{ rabbitmq_server_host }}{{ rabbitmq_server_vpath }}"

# +============================+

package_name: onlyoffice-documentserver

# +============================+

onlyoffice_username: onlyoffice
onlyoffice_userpass: onlyoffice
onlyoffice_domain:

# +============================+

email:

# +============================+

onlyoffice_with_nextcloud: 1 

# +============================+

state:

# +============================+

collabora_domain:

# +============================+

webserver:

# +============================+

dbtype:

# +============================+

draw_domain:

# +============================+
