- name: Checking Packages
  command: dpkg-query -l python-mysqldb
  register: pythondb_check

- name: Checking More packages
  command: dpkg-query -l mysql-server
  register: sqlserver_check

- name: Install python-mysqldb
  apt:
    name: python-mysqldb
    state: latest
  when: python-mysqldb.stdout.find('no packages found') != -1

- name: Install mysql-server
  apt:
    name: mysql-server
    state: latest
  when: sqlserver_check.stdout.find('no packages found') != -1

- name: copy .my.cnf file with root password credentials
  template: 
    src: "{{autocloud_dir}}/auto-cloud/roles/mysql/templates/.my.cnf"
    dest: ~/.my.cnf
    owner: root
    mode: 0600

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

- name: Set the root password
  mysql_user:
    user: root
    password: root
    host: localhost

- name: Delete anonymous user
  mysql_user:
    login_user: root
    login_password: root
    user: ""
    host_all: yes
    state: absent

- name: Remove the test database
  mysql_db:
    login_user: root
    login_password: root
    db: test
    state: absent