- name: Install packages
  apt:
    name: ['python-mysqldb','mysql-server']
    state: latest
  become: yes

- name: copy .my.cnf file with root password credentials
  template: 
    src: "{{autocloud_dir}}/roles/mysql/templates/my.cnf"
    dest: ~/.my.cnf
    owner: root
    mode: 0600

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

- name: Set the root password
  mysql_user:
    user: root
    password: root
    host: localhost

- name: Delete anonymous user
  mysql_user:
    login_user: root
    login_password: root
    user: ""
    host_all: yes
    state: absent

- name: Remove the test database
  mysql_db:
    login_user: root
    login_password: root
    db: test
    state: absent