---

- name: Install php dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - "php{{php_version}}-fpm"
    - "php{{php_version}}-gd"
    - "php{{php_version}}-json"
    - "php{{php_version}}-pgsql"
    - "php{{php_version}}-curl"
    - "php{{php_version}}-mbstring"
    - "php{{php_version}}-intl"
    - "php-imagick"
    - "php{{php_version}}-xml"
    - "php{{php_version}}-zip"
    - unzip
  become: yes

- name: configure php mysql module
  copy:
    dest: /etc/php/{{php_version}}/mods-available/pdo_mysql.ini
    content: |
      # configuration for PHP MySQL module
      extension=pdo_mysql.so

      [mysql]
      mysql.allow_local_infile=On
      mysql.allow_persistent=On
      mysql.cache_size=2000
      mysql.max_persistent=-1
      mysql.max_links=-1
      mysql.default_port=
      mysql.default_socket=/var/lib/mysql/mysql.sock
      mysql.default_host=
      mysql.default_user=
      mysql.default_password=
      mysql.connect_timeout=60
      mysql.trace_mode=Off
    owner: root
    group: root
    mode: 0644
  when: dbtype == "m"

- name: restart php-fpm
  systemd:
    name: "php{{php_version}}-fpm"
    state: restarted

- name: configure php
  copy:
    src: "{{autocloud_dir}}/roles/php/files/www.conf"
    dest: "/etc/php/{{php_version}}/fpm/pool.d/www.conf"
    owner: root
    group: root
    mode: 0644
    force: true

- name: restart php-fpm
  systemd:
    name: "php{{php_version}}-fpm"
    state: restarted

- name: enable php-fpm
  systemd:
    name: "php{{php_version}}-fpm"
    state: started
    enabled: true
