- name: Cloning webapp
  git:
    repo: 'https://github.com/jgraph/drawio.git'
    dest: /tmp/drawio
  become: yes

- name: Copying webapp
  command: cp -r /tmp/drawio/src/main/webapp /var/www/
  become: yes

- name: Setting owner
  command: chown www-data:www-data /var/www/webapp
  become: yes

- name: Setting up NGINX config file
  template:
    src: "{{autocloud_dir}}/roles/draw/templates/draw-nginx-local.conf.tpl"
    dest: "/etc/nginx/conf.d/{{draw_domain}}.conf"
  become: yes
  when: webserver == "n" and state == "l"

- name: Setting up NGINX config file
  template:
    src: "{{autocloud_dir}}/roles/draw/templates/draw-nginx-official.conf.tpl"
    dest: "/etc/nginx/conf.d/{{draw_domain}}.conf"
  become: yes
  when: webserver == "n" and state == "o"

- name: Checking ssl folder
  stat:
    path: /var/www/webapp/ssl
  register: ssl_check
  when: state == "l"

- name: Creating ssl folder
  file:
    path: /var/www/webapp/ssl
    state: directory
  become: yes
  when: state == "l"

- name: Setting up SSLCertificate file
  template:
    src: "ssl/draw.crt"
    dest: "/var/www/webapp/ssl/draw.crt"
  become: yes
  when: state == "l"

- name: Setting up SSLCertificateKey file
  template:
    src: "ssl/draw.key"
    dest: "/var/www/webapp/draw.key"
  become: yes
  when: state == "l"

- name: Generating SSL Certificate
  shell: letsencrypt --authenticator standalone --installer nginx -d {{draw_domain}} --email {{email}} --agree-tos -n --no-verify-ssl --redirect
  when: state == "o" and webserver == "n"